sudo: required
services:
   - docker

before_install:
   - docker build -t anushakv71/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true  anushakv71/react-test npm test -- --coverage

after_success:
   - docker build -t anushakv71/multi-client ./client
   - docker build -t anushakv71/multi-nginx ./nginx
   - docker build -t anushakv71/multi-server ./server
   - docker build -t anushakv71/multi-worker ./worker

#Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push these images to docker hub
   - docker push anushakv71/multi-client
   - docker push anushakv71/multi-nginx 
   - docker push anushakv71/multi-server
   - docker push anushakv71/multi-worker



